AssetManagementSystemUI/Controllers/BookUIController.cs
namespace AssetManagementSystemUI
{
    [Route("Book/[action]")]
    public class BookUIController : Controller
    {
        private readonly HelperAPI _api = new HelperAPI();

        private readonly AssetService assetService;

        public BookUIController(AssetService _assetService)
        {
            this.assetService = _assetService;
        }

        //[Route("display")]
        public async Task<IActionResult> Index()
        {

			List<BookViewModel> books = new List<BookViewModel>();
            using (HttpClient client = _api.Initial())
            {
                HttpResponseMessage res = await client.GetAsync("api/AssetDetail/Display");

                if (res.IsSuccessStatusCode)
                {
                    var result = res.Content.ReadAsStringAsync().Result;
                    books = JsonConvert.DeserializeObject<List<BookViewModel>>(result);
                    books = books.Where(i => i.CategoryId == (int)Assets.Book).ToList();
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Server error. Please contact administrator.");
                }
                return View(books);
            }
        }

        public ActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Add(BookViewModel book)
        {
            string _token = HttpContext.Session.GetString("_admintoken");

            using (HttpClient client = _api.Initial())
            {
                book.CategoryId = (int)Assets.Book;
                book.SerialId = assetService.GetCategories().Result.Where(i => i.Name == Assets.Book.ToString()).Select(i => i.SerialId).FirstOrDefault() + (new Random()).Next(100, 1000).ToString();
                client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue(scheme: "Bearer", parameter: _token);

                if (ModelState.IsValid)
                {
                    var postTask = client.PostAsJsonAsync<BookViewModel>("api/AssetDetail/Add", book);
                    postTask.Wait();

                    var result = postTask.Result;

                    if (result.IsSuccessStatusCode)
                    {
                        TempData["msg"] = "Book Added Sucessfully";
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        return RedirectToAction("~/Views/Shared/UnAuthorized.cshtml");
                    }
                }
                return View();
            }
        }

        public async Task<IActionResult> Edit(int id)
        {
            BookViewModel book = new BookViewModel();
            string _token = HttpContext.Session.GetString("_admintoken");
            using (HttpClient client = _api.Initial())
            {
                client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue(scheme: "Bearer", parameter: _token);

                HttpResponseMessage res = await client.GetAsync($"api/AssetDetail/Search/{id}");

                if (res.IsSuccessStatusCode)
                {
                    var result = res.Content.ReadAsStringAsync().Result;
                    book = JsonConvert.DeserializeObject<BookViewModel>(result);

                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Server error. Please contact administrator.");
                }


                return View(book);
            }
        }

        [HttpPost]
        public IActionResult Edit(BookViewModel book)
        {
            string _token = HttpContext.Session.GetString("_admintoken");
            using (HttpClient client = _api.Initial())
            {
                client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue(scheme: "Bearer", parameter: _token);
                if (ModelState.IsValid)
                {
                    var putTask = client.PutAsJsonAsync<BookViewModel>($"api/AssetDetail/Update/{book.Id}", book);
                    putTask.Wait();

                    var result = putTask.Result;

                    if (result.IsSuccessStatusCode)
                    {
                        TempData["msg"] = "Book Updated Sucessfully";
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        TempData["msg"] = "You are currently unauthorized";
                        return RedirectToAction("Index");
                    }
                }
                return View();
            }
        }
        public async Task<IActionResult> Delete(int id)
        {
            string _token = HttpContext.Session.GetString("_admintoken");
            using (HttpClient client = _api.Initial())
            {
                client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue(scheme: "Bearer", parameter: _token);
                HttpResponseMessage res = await client.DeleteAsync($"api/AssetDetail/Delete/{id}");

                if (res.IsSuccessStatusCode)
                {
                    TempData["msg"] = "Book Deleted Sucessfully";
                    return RedirectToAction("Index");
                }
                else
                {
                    TempData["msg"] = "You are currently unauthorized";
                    return RedirectToAction("Index");
                }
            }
        }
    }
}

AssetManagementSystemUI/Controllers/HardwareUIController.cs
namespace AssetManagementSystemUI
{
    [Route("Hardware/[action]")]
    public class HardwareUIController : Controller
    {
        private readonly HelperAPI _api = new HelperAPI();

        private readonly AssetService assetService;

        public HardwareUIController(AssetService _assetService)
        {
            this.assetService = _assetService;
        }
        public async Task<IActionResult> Display()
        {
            List<HardwareViewModel> hardwares = new List<HardwareViewModel>();
            using (HttpClient _client = _api.Initial())
            {

                HttpResponseMessage res = await _client.GetAsync("api/AssetDetail/Display");

                if (res.IsSuccessStatusCode)
                {
                    var result = res.Content.ReadAsStringAsync().Result;
                    hardwares = JsonConvert.DeserializeObject<List<HardwareViewModel>>(result);
                    hardwares = hardwares.Where(x => x.CategoryId == (int)Assets.Hardware).ToList();
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Server error. Please contact administrator.");
                }
                return View(hardwares);
            }   
        }

        public ActionResult Add()
        {
            string token = HttpContext.Session.GetString("_admintoken");
            if (token == null)
            {
                TempData["errormsg"] = "You are Unauthorized to visit this page";
                return RedirectToAction("AdminLogin", "Admin");
            }
            return View();
        }

        [HttpPost]
        public IActionResult Add(HardwareViewModel hardware)
        {
            string _token = HttpContext.Session.GetString("_admintoken");
            using (HttpClient client = _api.Initial())
            {
                hardware.CategoryId = (int)Assets.Hardware;
                hardware.SerialId = assetService.GetCategories().Result.Where(i => i.Name == Assets.Hardware.ToString()).Select(i => i.SerialId).FirstOrDefault() + (new Random()).Next(100, 1000).ToString();
                client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue(scheme: "Bearer", parameter: _token);

                if (ModelState.IsValid)
                {
                    var postTask = client.PostAsJsonAsync<HardwareViewModel>("api/AssetDetail/Add", hardware);
                    postTask.Wait();

                    var result = postTask.Result;

                    if (result.IsSuccessStatusCode)
                    {
                        TempData["msg"] = "Hardware Added Sucessfully";
                        return RedirectToAction("Display");
                    }
                    else
                    {
                        TempData["msg"] = "You are currently unauthorized";
                        return RedirectToAction("Display");
                    }
                }
                return View();
            }
        }

        public async Task<IActionResult> Edit(int id)
        {
            HardwareViewModel hardware = new HardwareViewModel();
            string _token = HttpContext.Session.GetString("_admintoken");
            using (HttpClient client = _api.Initial())
            {
                client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue(scheme: "Bearer", parameter: _token);
                HttpResponseMessage res = await client.GetAsync($"api/AssetDetail/Search/{id}");

                if (res.IsSuccessStatusCode)
                {
                    var result = res.Content.ReadAsStringAsync().Result;
                    hardware = JsonConvert.DeserializeObject<HardwareViewModel>(result);

                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Server error. Please contact administrator.");
                }


                return View(hardware);
            }
        }

        [HttpPost]
        public IActionResult Edit(HardwareViewModel hardware)
        {
            string _token = HttpContext.Session.GetString("_admintoken");
            using (HttpClient client = _api.Initial())
            {
                client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue(scheme: "Bearer", parameter: _token);
                if (ModelState.IsValid)
                {
                    var putTask = client.PutAsJsonAsync<HardwareViewModel>($"api/AssetDetail/Update/{hardware.Id}", hardware);
                    putTask.Wait();

                    var result = putTask.Result;

                    if (result.IsSuccessStatusCode)
                    {
                        TempData["msg"] = "Hardware Updated Sucessfully";
                        return RedirectToAction("Display");
                    }
                    else
                    {
                        TempData["msg"] = "You are currently unauthorized";
                        return RedirectToAction("Display");
                    }
                }
                return View();
            }
        }

        public async Task<IActionResult> Delete(int id)
        {
            string _token = HttpContext.Session.GetString("_admintoken");
            using (HttpClient client = _api.Initial())
            {
                client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue(scheme: "Bearer", parameter: _token);
                HttpResponseMessage res = await client.DeleteAsync($"api/AssetDetail/Delete/{id}");

                if (res.IsSuccessStatusCode)
                {
                    TempData["msg"] = "Hardware Deleted Sucessfully";
                    return RedirectToAction("Display");
                }
                else
                {
                    TempData["msg"] = "You are currently unauthorized";
                    return RedirectToAction("Display");
                }
            }
        }
    }
}

AssetManagementSystemUI/Controllers/SoftwareUIController.cs
namespace AssetManagementSystemUI
{
    [Route("Software/[action]")]
    public class SoftwareUIController : Controller
    {
        private readonly HelperAPI _api = new();

        private readonly AssetService assetService;

        public SoftwareUIController(AssetService _assetService)
        {
            this.assetService = _assetService;
        }
        public async Task<IActionResult> Display()
        {
            List<SoftwareViewModel> softwares = new List<SoftwareViewModel>();

            using (HttpClient client = _api.Initial())
            {
                HttpResponseMessage res = await client.GetAsync("api/AssetDetail/Display");

                if (res.IsSuccessStatusCode)
                {
                    var result = res.Content.ReadAsStringAsync().Result;
                    softwares = JsonConvert.DeserializeObject<List<SoftwareViewModel>>(result);
                    softwares = softwares.Where(x => x.CategoryId == (int)Assets.Software).ToList();
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Server error. Please contact administrator.");
                }
                return View(softwares);
            }
        }

        public ActionResult Add()
        {
            string token = HttpContext.Session.GetString("_admintoken");
            if (token == null)
            {
                TempData["errormsg"] = "You are Unauthorized to visit this page";
                return RedirectToAction("AdminLogin", "Admin");
            }

            return View();
        }

        [HttpPost]
        public IActionResult Add(SoftwareViewModel software)
        {
            string _token = HttpContext.Session.GetString("_admintoken");
            using (HttpClient client = _api.Initial())
            {
                software.CategoryId = (int)Assets.Software;
                software.SerialId = assetService.GetCategories().Result.Where(i => i.Name == Assets.Software.ToString()).Select(i => i.SerialId).FirstOrDefault() + (new Random()).Next(100, 1000).ToString();
                client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue(scheme: "Bearer", parameter: _token);

                if (ModelState.IsValid)
                {
                    var postTask = client.PostAsJsonAsync<SoftwareViewModel>("api/AssetDetail/Add", software);
                    postTask.Wait();

                    var result = postTask.Result;

                    if (result.IsSuccessStatusCode)
                    {
                        TempData["msg"] = "Software Added Sucessfully";
                        return RedirectToAction("Display");
                    }
                    else
                    {
                        TempData["msg"] = "You are currently unauthorized";
                        return RedirectToAction("Display");
                    }
                }
                return View();
            }
        }

        public async Task<IActionResult> Edit(int id)
        {
            SoftwareViewModel software = new SoftwareViewModel();
            string _token = HttpContext.Session.GetString("_admintoken");

            using (HttpClient client = _api.Initial())
            {
                client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue(scheme: "Bearer", parameter: _token);
                HttpResponseMessage res = await client.GetAsync($"api/AssetDetail/Search/{id}");

                if (res.IsSuccessStatusCode)
                {
                    var result = res.Content.ReadAsStringAsync().Result;
                    software = JsonConvert.DeserializeObject<SoftwareViewModel>(result);

                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Server error. Please contact administrator.");
                }


                return View(software);
            }
        }

        [HttpPost]
        public IActionResult Edit(SoftwareViewModel software)
        {
            string _token = HttpContext.Session.GetString("_admintoken");

            using (HttpClient client = _api.Initial())
            {
                client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue(scheme: "Bearer", parameter: _token);

                if (ModelState.IsValid)
                {
                    var putTask = client.PutAsJsonAsync<SoftwareViewModel>($"api/AssetDetail/Update/{software.Id}", software);
                    putTask.Wait();

                    var result = putTask.Result;

                    if (result.IsSuccessStatusCode)
                    {
                        TempData["msg"] = "Software Updated Sucessfully";
                        return RedirectToAction("Display");
                    }
                    else
                    {
                        TempData["msg"] = "You are currently unauthorized";
                        return RedirectToAction("Display");
                    }
                }
                return View();
            }
        }

        public async Task<IActionResult> Delete(int id)
        {
            string _token = HttpContext.Session.GetString("_admintoken");

            using (HttpClient client = _api.Initial())
            {
                client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue(scheme: "Bearer", parameter: _token);
                HttpResponseMessage res = await client.DeleteAsync($"api/AssetDetail/Delete/{id}");

                if (res.IsSuccessStatusCode)
                {
                    TempData["msg"] = "Software Deleted Sucessfully";
                    return RedirectToAction("Display");
                }
                else
                {
                    TempData["msg"] = "You are currently unauthorized";
                    return RedirectToAction("Display");
                }
            }
        }
    }
}

AssetManagementSystemUI/Views/Admin/AdminLogin.cshtml
@model AssetManagementSystemUI.UserViewModel

@{
    ViewData["Title"] = "Admin Login";
    Layout = "~/Views/Shared/_loginLayout.cshtml";
}

<h5>Admin Login</h5>

<hr />
<div class="row">
    <div class="col-md-4">
        <strong style="color: red">@TempData["errormsg"]</strong>
        <form asp-action="AdminLogin">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" type="email"/>
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" type="password"/>
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Login" class="btn btn-outline-primary" />
            </div>
        </form>

        <div>
            <a asp-area="" asp-controller="UserUI" asp-action="Login">Login as User</a>
        </div>
    </div>
</div>

AssetManagementSystemUI/Views/Admin/Assign.cshtml
@model AssetManagementSystemUI.AssetViewModel

@{
    ViewData["Title"] = "Assign Asset";
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
    Layout = "~/Views/Shared/_otherLayout.cshtml";
}
    <script>
        $(document).ready(function () {
        });

        $(document).ready(function () {
            $('#assetType').change(function () {
            var selectionval = (this.value);
            var markup = "<option value='0'>--Select Asset Type--</option>";
                console.log("change function selection");
                $("#assetGenre").html('');
                $("#assetName").html('');
                $.ajax({
                    type: "POST",
                    dataType: "JSON",
                    url: "/Asset/GetAssetType",
                    data: { filter: selectionval },
                    success:
                        function (data) {
                            console.log(data);
                            for (var i = 0; i < data.length; i++) {
                                markup += "<option value=" + selectionval + ">" + data[i] + "</option>";
                                console.log("po" + data[i]);
                            }
                            $("#assetGenre").append(markup);
                            $("#assetGenreDiv").show();
                        },
                    error: function (data) {
                        alert("error" + data);
                    }
                })
            });
        });

        $(document).ready(function () {
            $('#assetGenre').change(function () {
                var selectionval = (this.value);
                var markup = "<option value='0'>--Select Asset Name--</option>";
                var text = $(this).find("option:selected").text();
                $("#assetName").html('');
                $.ajax({
                    type: "POST",
                    dataType: "JSON",
                    url: "/Asset/GetAssets",
                    data: { filter: selectionval, genre: text },
                    success:
                        function (data) {
                            console.log(data);                           
                            for (var i = 0; i < data.length; i++) {
                                markup += "<option value=" + data[i].id + ">" + data[i].name + "</option>";
                            }
                            $("#assetName").append(markup);
                            $("#assetNameDiv").show();
                        },
                    error: function (data) {
                        alert("error" + data);
                    }
                })
            });
        });

    </script>

    <h5>Assign</h5>
    <hr />
    <div class="row">
    <div class="col-md-4">
        <p style="color: red">@TempData["msg"]</p>
            <form asp-action="Assign">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                <div class="form-group">
                    @Html.LabelFor(x => x.AssetName, htmlAttributes: new { @class = "control-label" })
                    <select class="form-control" id="assetType" name="Filter" asp-for="AssetName">
                        <option value="0">--Select Asset--</option>
                        <option value="1">Books</option>
                        <option value="2">Software</option>
                        <option value="3">Hardware</option>
                    </select>
                </div>

                <br />
                <div class="form-group" id="assetGenreDiv">
                    <label for="assetGenre">Asset Type</label>
                    <div>
                        <select class="form-control" id="assetGenre" name="assetGenre" title="assetGenre"></select>
                    </div>
                </div>

                <br />
                <div class="form-group" id="assetNameDiv">
                <label for="assetName">Asset Name</label>
                    <div>
                        <select class="form-control" id="assetName" name="assetName" title="assetName"></select>
                    </div>
                </div>

                <br />
                <div class="form-group">
                    @Html.LabelFor(x => x.UserEmail, htmlAttributes: new { @class = "control-label" })
                    <div>
                        <input asp-for="UserEmail" class="form-control" type="email"/>
                        <span asp-validation-for="UserEmail" class="text-danger"></span>
                    </div>
                </div>

                <br />
                <div class="form-group">
                    @Html.LabelFor(x => x.DateOfReturn, htmlAttributes: new { @class = "control-label" })
                    <div>
                        <input asp-for="DateOfReturn" class="form-control" />
                        <span asp-validation-for="DateOfReturn" class="text-danger"></span>
                    </div>
                </div>
                <br />
                <div class="form-group">
                    <input type="submit" value="Save" class="btn btn-outline-primary" />
                </div>
            </form>
        </div>
    </div>

AssetManagementSystemUI/Views/Admin/DeclineRequest.cshtml
@model AssetManagementSystemUI.AssetViewModel

@{
    ViewData["Title"] = "Display Asset Request";
    Layout = "~/Views/Shared/_otherLayout.cshtml";
}

<h6>Give a reason for declining this request?</h6>
<div>
    <hr />

    <form asp-action="DeclineRequest" method="post">
    <dl class="row">
        <dd>
            @Html.HiddenFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AssetName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AssetName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AssignedAsset)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AssignedAsset)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateOfReturn)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateOfReturn)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UserEmail)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UserEmail)
        </dd>
        <div class="form-group">
            @Html.LabelFor(x => x.Reason, htmlAttributes: new { @class = "control-label required" })
            <input asp-for="Reason" class="form-control" type="text" />
            <span asp-validation-for="Reason" class="text-danger"></span>
        </div>
    </dl>
    
        <input type="submit" value="Confirm" class="btn btn-danger" />
    </form>
</div>

AssetManagementSystemUI/Views/Admin/Index.cshtml
@{
    ViewData["Title"] = "Staff Page";
}

<style>
    .navbar {
        background-color: skyblue;
    }

    .dropdown {
      position: relative;
      display: inline-block;
      padding: 10px;
    }

    .dropdown-content {
      display: none;
      position: absolute;
      background-color: #f9f9f9;
      min-width: 160px;
      box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
      z-index: 1;
    }

    .dropdown-content a {
      color: black;
      padding: 12px 16px;
      text-decoration: none;
      display: block;
    }

    .dropdown-content a:hover {background-color: #f1f1f1}

    .dropdown:hover .dropdown-content {
      display: block;
    }
</style>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Asset Management System</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Hdhuwehdome</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privsajdnkacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
</body>

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <div>
        <div class="dropdown">
            <button class="dropbtn">Book</button>
            <div class="dropdown-content">
                <a class="text-dark" asp-area="" asp-controller="BookUI" asp-action="Index">Display</a>
                <a class="text-dark" asp-area="" asp-controller="BookUI" asp-action="Add">Add</a>
            </div>
        </div>
        <div class="dropdown">
            <button class="dropbtn">Software</button>
            <div class="dropdown-content">
                <a class="text-dark" asp-area="" asp-controller="SoftwareUI" asp-action="Display">Display</a>
                <a class="text-dark" asp-area="" asp-controller="SoftwareUI" asp-action="Add">Add</a>
            </div>
        </div>
        <div class="dropdown">
            <button class="dropbtn">Hardware</button>
            <div class="dropdown-content">
                <a class="text-dark" asp-area="" asp-controller="HardwareUI" asp-action="Display">Display</a>
                <a class="text-dark" asp-area="" asp-controller="HardwareUI" asp-action="Add">Add</a>
            </div>
        </div>
    </div>
</div>

AssetManagementSystemUI/Views/Admin/Login.cshtml
@model AssetManagementSystemUI.Login

@{
    ViewData["Title"] = "Login";
    <p style="color:red">@TempData["errormsg"]</p>
}

<h4>Login</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Login">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" type="password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Login" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
<br />
<div>
    <a asp-controller="Home" asp-action="Login">Login as User</a>
</div>