AssetManagementSystemUI/Controllers/AssetUIController.cs
namespace AssetManagementSystemUI
{
    [Route("Asset/[action]")]
    public class AssetUIController : Controller
    {
        private readonly IHttpContextAccessor _httpContextAccessor;

        private readonly AssetService assetService;

        public AssetUIController(AssetService _assetService, IHttpContextAccessor httpContextAccessor)
        {
            this.assetService = _assetService;
            this._httpContextAccessor = httpContextAccessor;
        }

        public ActionResult<AssetViewModel> Display()
        {
            try
            {
                var asset = assetService.GetAssetViews().Result.Where(i => i.Status == Status.Assigned.ToString() || i.Status == Status.Unassigned.ToString()).ToList();
                if(asset == null)
                {
                    return View("UnAuthorized");
                }
                return View(asset);
            }
            catch
            {
                return RedirectToAction("Services", "Admin");
            }
        }

        [HttpPost]
        public ActionResult<AssetViewModel> Display(string all)
        {
            try
            {
                return View(assetService.GetFilteredAsset(all).Where(i => i.Status == Status.Assigned.ToString() || i.Status == Status.Unassigned.ToString()).ToList());
            }
            catch
            {
                return RedirectToAction("Services", "Admin");
            }
        }

        [HttpPost]
        public ActionResult GetAssets(string filter, string genre)
        {
            return Json(assetService.GetAssetDetails(filter, genre));
        }

        [HttpPost]
        public ActionResult GetAssetType(string filter) 
        {
            return Json(assetService.GetAssetType(filter));
        }

        public ActionResult<AssetViewModel> DisplayRequest()
        {
            try
            {
                return View(assetService.GetAssetViews().Result.Where(i => i.Status == Status.Request.ToString()));
            }
            catch
            {
                return View(null);
            }
        }

        [HttpPost]
        public ActionResult<AssetViewModel> DisplayRequest(string all)
        {
            try
            {
                return View(assetService.GetFilteredAsset(all).Where(i => i.Status == Status.Request.ToString() || i.Status == Status.Decline.ToString()));

            }
            catch
            {
                return RedirectToAction("Services", "Admin");
            }
        }

        public ActionResult<AssetViewModel> History()
        {
            try
            {
                var asset = assetService.GetAssetViews().Result;
                if(asset == null)
                {
                    return View("UnAuthorized");
                }
                return View(asset);
            }
            catch 
            { 
                return View(null); 
            }
        }

        [HttpPost]
        public ActionResult<AssetViewModel> History(string all)
        {
            return View(assetService.GetFilteredAsset(all));
        }
    }
}

AssetManagementSystemUI/Controllers/BookUIController.cs
namespace AssetManagementSystemUI
{
    [Route("Book/[action]")]
    public class BookUIController : Controller
    {
        private readonly HelperAPI _api = new HelperAPI();

        private readonly AssetService assetService;

        public BookUIController(AssetService _assetService)
        {
            this.assetService = _assetService;
        }

        //[Route("display")]
        public async Task<IActionResult> Index()
        {

			List<BookViewModel> books = new List<BookViewModel>();
            using (HttpClient client = _api.Initial())
            {
                HttpResponseMessage res = await client.GetAsync("api/AssetDetail/Display");

                if (res.IsSuccessStatusCode)
                {
                    var result = res.Content.ReadAsStringAsync().Result;
                    books = JsonConvert.DeserializeObject<List<BookViewModel>>(result);
                    books = books.Where(i => i.CategoryId == (int)Assets.Book).ToList();
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Server error. Please contact administrator.");
                }
                return View(books);
            }
        }

        public ActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Add(BookViewModel book)
        {
            string _token = HttpContext.Session.GetString("_admintoken");

            using (HttpClient client = _api.Initial())
            {
                book.CategoryId = (int)Assets.Book;
                book.SerialId = assetService.GetCategories().Result.Where(i => i.Name == Assets.Book.ToString()).Select(i => i.SerialId).FirstOrDefault() + (new Random()).Next(100, 1000).ToString();
                client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue(scheme: "Bearer", parameter: _token);

                if (ModelState.IsValid)
                {
                    var postTask = client.PostAsJsonAsync<BookViewModel>("api/AssetDetail/Add", book);
                    postTask.Wait();

                    var result = postTask.Result;

                    if (result.IsSuccessStatusCode)
                    {
                        TempData["msg"] = "Book Added Sucessfully";
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        return RedirectToAction("~/Views/Shared/UnAuthorized.cshtml");
                    }
                }
                return View();
            }
        }

        public async Task<IActionResult> Edit(int id)
        {
            BookViewModel book = new BookViewModel();
            string _token = HttpContext.Session.GetString("_admintoken");
            using (HttpClient client = _api.Initial())
            {
                client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue(scheme: "Bearer", parameter: _token);

                HttpResponseMessage res = await client.GetAsync($"api/AssetDetail/Search/{id}");

                if (res.IsSuccessStatusCode)
                {
                    var result = res.Content.ReadAsStringAsync().Result;
                    book = JsonConvert.DeserializeObject<BookViewModel>(result);

                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Server error. Please contact administrator.");
                }


                return View(book);
            }
        }

        [HttpPost]
        public IActionResult Edit(BookViewModel book)
        {
            string _token = HttpContext.Session.GetString("_admintoken");
            using (HttpClient client = _api.Initial())
            {
                client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue(scheme: "Bearer", parameter: _token);
                if (ModelState.IsValid)
                {
                    var putTask = client.PutAsJsonAsync<BookViewModel>($"api/AssetDetail/Update/{book.Id}", book);
                    putTask.Wait();

                    var result = putTask.Result;

                    if (result.IsSuccessStatusCode)
                    {
                        TempData["msg"] = "Book Updated Sucessfully";
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        TempData["msg"] = "You are currently unauthorized";
                        return RedirectToAction("Index");
                    }
                }
                return View();
            }
        }
        public async Task<IActionResult> Delete(int id)
        {
            string _token = HttpContext.Session.GetString("_admintoken");
            using (HttpClient client = _api.Initial())
            {
                client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue(scheme: "Bearer", parameter: _token);
                HttpResponseMessage res = await client.DeleteAsync($"api/AssetDetail/Delete/{id}");

                if (res.IsSuccessStatusCode)
                {
                    TempData["msg"] = "Book Deleted Sucessfully";
                    return RedirectToAction("Index");
                }
                else
                {
                    TempData["msg"] = "You are currently unauthorized";
                    return RedirectToAction("Index");
                }
            }
        }
    }
}

AssetManagementSystemUI/Controllers/HardwareUIController.cs
namespace AssetManagementSystemUI
{
    [Route("Hardware/[action]")]
    public class HardwareUIController : Controller
    {
        private readonly HelperAPI _api = new HelperAPI();

        private readonly AssetService assetService;

        public HardwareUIController(AssetService _assetService)
        {
            this.assetService = _assetService;
        }
        public async Task<IActionResult> Display()
        {
            List<HardwareViewModel> hardwares = new List<HardwareViewModel>();
            using (HttpClient _client = _api.Initial())
            {

                HttpResponseMessage res = await _client.GetAsync("api/AssetDetail/Display");

                if (res.IsSuccessStatusCode)
                {
                    var result = res.Content.ReadAsStringAsync().Result;
                    hardwares = JsonConvert.DeserializeObject<List<HardwareViewModel>>(result);
                    hardwares = hardwares.Where(x => x.CategoryId == (int)Assets.Hardware).ToList();
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Server error. Please contact administrator.");
                }
                return View(hardwares);
            }   
        }

        public ActionResult Add()
        {
            string token = HttpContext.Session.GetString("_admintoken");
            if (token == null)
            {
                TempData["errormsg"] = "You are Unauthorized to visit this page";
                return RedirectToAction("AdminLogin", "Admin");
            }
            return View();
        }

        [HttpPost]
        public IActionResult Add(HardwareViewModel hardware)
        {
            string _token = HttpContext.Session.GetString("_admintoken");
            using (HttpClient client = _api.Initial())
            {
                hardware.CategoryId = (int)Assets.Hardware;
                hardware.SerialId = assetService.GetCategories().Result.Where(i => i.Name == Assets.Hardware.ToString()).Select(i => i.SerialId).FirstOrDefault() + (new Random()).Next(100, 1000).ToString();
                client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue(scheme: "Bearer", parameter: _token);

                if (ModelState.IsValid)
                {
                    var postTask = client.PostAsJsonAsync<HardwareViewModel>("api/AssetDetail/Add", hardware);
                    postTask.Wait();

                    var result = postTask.Result;

                    if (result.IsSuccessStatusCode)
                    {
                        TempData["msg"] = "Hardware Added Sucessfully";
                        return RedirectToAction("Display");
                    }
                    else
                    {
                        TempData["msg"] = "You are currently unauthorized";
                        return RedirectToAction("Display");
                    }
                }
                return View();
            }
        }

        public async Task<IActionResult> Edit(int id)
        {
            HardwareViewModel hardware = new HardwareViewModel();
            string _token = HttpContext.Session.GetString("_admintoken");
            using (HttpClient client = _api.Initial())
            {
                client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue(scheme: "Bearer", parameter: _token);
                HttpResponseMessage res = await client.GetAsync($"api/AssetDetail/Search/{id}");

                if (res.IsSuccessStatusCode)
                {
                    var result = res.Content.ReadAsStringAsync().Result;
                    hardware = JsonConvert.DeserializeObject<HardwareViewModel>(result);

                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Server error. Please contact administrator.");
                }


                return View(hardware);
            }
        }

        [HttpPost]
        public IActionResult Edit(HardwareViewModel hardware)
        {
            string _token = HttpContext.Session.GetString("_admintoken");
            using (HttpClient client = _api.Initial())
            {
                client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue(scheme: "Bearer", parameter: _token);
                if (ModelState.IsValid)
                {
                    var putTask = client.PutAsJsonAsync<HardwareViewModel>($"api/AssetDetail/Update/{hardware.Id}", hardware);
                    putTask.Wait();

                    var result = putTask.Result;

                    if (result.IsSuccessStatusCode)
                    {
                        TempData["msg"] = "Hardware Updated Sucessfully";
                        return RedirectToAction("Display");
                    }
                    else
                    {
                        TempData["msg"] = "You are currently unauthorized";
                        return RedirectToAction("Display");
                    }
                }
                return View();
            }
        }

        public async Task<IActionResult> Delete(int id)
        {
            string _token = HttpContext.Session.GetString("_admintoken");
            using (HttpClient client = _api.Initial())
            {
                client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue(scheme: "Bearer", parameter: _token);
                HttpResponseMessage res = await client.DeleteAsync($"api/AssetDetail/Delete/{id}");

                if (res.IsSuccessStatusCode)
                {
                    TempData["msg"] = "Hardware Deleted Sucessfully";
                    return RedirectToAction("Display");
                }
                else
                {
                    TempData["msg"] = "You are currently unauthorized";
                    return RedirectToAction("Display");
                }
            }
        }
    }
}

AssetManagementSystemUI/Views/Shared/UnAuthorized.cshtml
@using Microsoft.AspNetCore.Http
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor

@{
    ViewData["Title"] = "401-UNAUTHROIZED";
    Layout = null;

    ViewBag.Token = HttpContextAccessor.HttpContext.Session.GetString("_token");
    ViewBag.AdminToken = HttpContextAccessor.HttpContext.Session.GetString("_admintoken");


}

<link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<style>
    body {
        background-image: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABoAAAAaCAYAAACpSkzOAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALEgAACxIB0t1+/AAAABZ0RVh0Q3JlYXRpb24gVGltZQAxMC8yOS8xMiKqq3kAAAAcdEVYdFNvZnR3YXJlAEFkb2JlIEZpcmV3b3JrcyBDUzVxteM2AAABHklEQVRIib2Vyw6EIAxFW5idr///Qx9sfG3pLEyJ3tAwi5EmBqRo7vHawiEEERHS6x7MTMxMVv6+z3tPMUYSkfTM/R0fEaG2bbMv+Gc4nZzn+dN4HAcREa3r+hi3bcuu68jLskhVIlW073tWaYlQ9+F9IpqmSfq+fwskhdO/AwmUTJXrOuaRQNeRkOd5lq7rXmS5InmERKoER/QMvUAPlZDHcZRhGN4CSeGY+aHMqgcks5RrHv/eeh455x5KrMq2yHQdibDO6ncG/KZWL7M8xDyS1/MIO0NJqdULLS81X6/X6aR0nqBSJcPeZnlZrzN477NKURn2Nus8sjzmEII0TfMiyxUuxphVWjpJkbx0btUnshRihVv70Bv8ItXq6Asoi/ZiCbU6YgAAAABJRU5ErkJggg==);
    }

    .error-template {
        padding: 40px 15px;
        text-align: center;
    }

    .error-actions {
        margin-top: 15px;
        margin-bottom: 15px;
    }

        .error-actions .btn {
            margin-right: 10px;
        }
</style>

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="error-template">
                <h1>
                    Oops!
                </h1>
                <h2>
                    401 Authorized
                </h2>
                <div class="error-details">
                    Sorry, an error has occured, You are not authorized to see the Requested page!
                </div>
                <div class="error-actions">
                    @if(ViewBag.Token != null)
                    {
                        <a asp-action="Index" asp-controller="User" class="btn btn-primary btn-lg">
                            <span class="glyphicon glyphicon-home"></span>
                            Take Me Home
                        </a>
                    }
                    @if (ViewBag.AdminToken != null)
                    {
                        <a asp-action="Services" asp-controller="Admin" class="btn btn-primary btn-lg">
                            <span class="glyphicon glyphicon-home"></span>
                            Take Me Home
                        </a>
                    }
                    <a asp-action="Login" asp-controller="UserUI" class="btn btn-primary btn-lg">
                        <span class="glyphicon glyphicon-home"></span>
                        Log Out
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>

AssetManagementSystemUI/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor


<!DOCTYPE html>

@{
    ViewBag.Token = HttpContextAccessor.HttpContext.Session.GetString("_token");
    ViewBag.AdminToken = HttpContextAccessor.HttpContext.Session.GetString("_admintoken");
    if(ViewBag.Token == null)
    {
            { await Html.RenderPartialAsync("UnAuthorized.cshtml"); }

            <main role="main" class="pb-3">
                @{
                    IgnoreBody();
                }
            </main>
        
    }  
    else
    {


<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/StyleSheet.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AssetManagementSystemUI.styles.css" asp-append-version="true" />
</head>
<body>
    <header class="navigation">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm box-shadow mb-3">
            <div class="container-fluid">
                <h5 class="navbar-brand">Asset Management System</h5>
                        <div class="navigation navbar navbar-collapse collapse d-sm-inline-flex justify-content-between">
                           <ul class="navbar-nav flex-grow-1">
                                <li class="nav-item" style="padding: 8px">
                                    <button onclick="@("window.location.href='" + @Url.Action("Index", "BookUI") + "'");" class="dropbtn">Books</button>
                                </li>
                                <li class="nav-item" style="padding: 8px">
                                    <button onclick="@("window.location.href='" + @Url.Action("Display", "SoftwareUI") + "'");" class="dropbtn">Software</button>
                                </li>
                                <li class="nav-item" style="padding: 8px">
                                    <button onclick="@("window.location.href='" + @Url.Action("Display", "HardwareUI") + "'");" class="dropbtn">Hardware</button>
                                </li>
                                <li class="nav-item" style="padding: 8px">
                                    <div class="dropdown">
                                        <button class="dropbtn">Assets</button>
                                        <div class="dropdown-content">
                                            <a class="text-dark" asp-area="" asp-controller="UserUI" asp-action="DisplayRequest">Display</a>
                                            <a class="text-dark" asp-area="" asp-controller="UserUI" asp-action="RequestAsset">Request</a>
                                        </div>
                                    </div>
                                </li>
                            </ul> 
                        </div>
                 <div class="dropdown">
                    <button class="dropbtn" style="margin-right: 50px">Profile</button>
                        <div class="dropdown-content">
                            <a class="text-dark" asp-area="" asp-controller="UserUI" asp-action="Profile">Visit Profile</a>
                            <a class="text-dark" asp-area="" asp-controller="UserUI" asp-action="Login">Log Out</a>
                        </div>
                 </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - AssetManagementSystem
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>
}
}

AssetManagementSystemUI/Views/Shared/_loginLayout.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/StyleSheet.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AssetManagementSystemUI.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <h5 class="navbar-brand">Asset Management System</h5>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - AssetManagementSystem
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

AssetManagementSystemUI/Views/Shared/_otherLayout.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
@using Microsoft.AspNetCore.Http
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor

<!DOCTYPE html>

@{
    ViewBag.Token = HttpContextAccessor.HttpContext.Session.GetString("_admintoken");
    ViewBag.UserToken = HttpContextAccessor.HttpContext.Session.GetString("_token");
    if(ViewBag.Token == null)
    {
            { await Html.RenderPartialAsync("UnAuthorized.cshtml"); }

            <main role="main" class="pb-3">
                @{
                    IgnoreBody();
                }
            </main>
        
    }
    else
    {
        
 

<html>
<head>
    
    <title>@ViewData["Title"]</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/StyleSheet.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AssetManagementSystemUI.styles.css" asp-append-version="true" />
</head>

<body>
    <header class="navigation">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-controller="AdminUI" asp-action="Services">Asset Management System</a>
               
                <div class="navigation navbar navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <div class="dropdown navigation">
                                <button class="dropbtn">Book</button>
                                <div class="dropdown-content">
                                    <a class="text-dark" asp-area="" asp-controller="BookUI" asp-action="Add">Add</a>
                                    <a class="text-dark" asp-area="" asp-controller="BookUI" asp-action="Index">Display</a>
                                </div>
                            </div>
                        </li>
                        <li class="nav-item">
                            <div class="dropdown navbar-nav flex-grow-1">
                                <button class="dropbtn">Software</button>
                                <div class="dropdown-content">
                                    <a class="text-dark" asp-area="" asp-controller="SoftwareUI" asp-action="Add">Add</a>
                                    <a class="text-dark" asp-area="" asp-controller="SoftwareUI" asp-action="Display">Display</a>
                                </div>
                            </div>
                        </li>
                        <li class="nav-item">
                            <div class="dropdown">
                                <button class="dropbtn">Hardware</button>
                                <div class="dropdown-content">
                                    <a class="text-dark" asp-area="" asp-controller="HardwareUI" asp-action="Add">Add</a>
                                    <a class="text-dark" asp-area="" asp-controller="HardwareUI" asp-action="Display">Display</a>
                                </div>
                            </div>
                        </li>
                        <li class="nav-item">
                            <div class="dropdown">
                                <button class="dropbtn">Assets</button>
                                <div class="dropdown-content">
                                    <a class="text-dark" asp-area="" asp-controller="Admin" asp-action="Assign">Assign</a>
                                    <a class="text-dark" asp-area="" asp-controller="AssetUI" asp-action="Display">Display</a>
                                    <a class="text-dark" asp-area="" asp-controller="AssetUI" asp-action="DisplayRequest">Requests</a>
                                    <a class="text-dark" asp-area="" asp-controller="AssetUI" asp-action="History">History</a>
                                </div>
                            </div>
                        </li>
                    </ul>
                </div>
                <a class="dropbtn" asp-area="" asp-controller="Admin" asp-action="AdminLogin">Log Out</a>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - AssetManagementSystem
        </div>
    </footer>
</body>
</html>
    }
}